Neos:
  Neos:
    fusion:
      autoInclude:
        'Carbon.GoogleTracking': true

Carbon:
  GoogleTracking:
    AddToPagePrototype: false
    # Including GTM-
    TagManager:  false
    # Including UA-
    Analytics:  false
    SiteVerification: false
